---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for Comments Microservice
Parameters:
  Stage:
    Type: String
  Bucket:
    Type: String
  Region:
    Type: String
  AccessKeyId:
    Type: String
  SecretAccessKey:
    Type: String
Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 180
    Handler: src/lambdas/comments/handler.execute
Resources:
  CommentsLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref Bucket
        Key: "sam/lambda-comments.zip"
      FunctionName: !Join [ "", [ !Ref Stage, "-CommentsLambda"] ]
      Environment:
        Variables:
          REGION: !Ref Region
          ACCESS_KEY_ID: !Ref AccessKeyId
          SECRET_ACCESS_KEY: !Ref SecretAccessKey
  CommentsLambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CommentsLambda
      Principal: "*"