---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for DynamoDB
Parameters:
  Stage:
    Type: String
Resources:
  CommentsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Join [ "", [ !Ref Stage, "-CommentsTable"] ]
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Join [ "", [ !Ref Stage, "-PostsTable"] ]
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2